# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/
relative_permalinks: false

# Setup
title:            Kai-Chieh (Jay) Weng
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme'
description:      'National Central University'
url:              https://factorialk.github.io/
baseurl:          "/"

author:
  name:           'Kai Jay Wong'
  # url:            https://twitter.com/mdo

paginate:         6
plugins:
  - jekyll-paginate

# Custom vars
version:          5.6.0

github:
  repo:           https://github.com/FactorialK

