# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/
relative_permalinks: false

# Setup
title:            Kai-Chieh (Jay) Weng
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://factorialk.github.io
baseurl:          /

author:
  name:           'Kai Jay Wong'
  # url:            https://twitter.com/mdo

paginate:         5
plugins:
  - jekyll-paginate

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/FactorialK

