# theme: minimal-mistakes-jekyll
theme: jekyll-theme-cayman
# remote_theme: "mmistakes/minimal-mistakes@4.26.2"


# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: Kai-Chieh (Jay) Weng
description: National Central University
url: https://FactorialK.github.io
baseurl: "/"

plugins:
  - jekyll-include-cache
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num"


# Navigation links
header_pages:
  - index.md
  - research.md

# Sidebar link settings
sidebar_home_link: true
