theme: jekyll-theme-minimal
# theme: minimal-mistakes-jekyll
# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Kai-Chieh (Jay) Weng
tagline:          ''
description:      'National Central University'
url:              FactorialK.github.io
baseurl:          '/'



paginate:         2
paginate_path:    'page:num'

plugins:
  - jekyll-include-cache

#   - jekyll-feed
#   - jekyll-gist
#   - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
#sidebar_blog_link:  '/'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
